openapi: 3.1.0
info:
  title: Auth API
  description: API for user authentication, including sign-up and sign-in.
  version: 1.0.0
paths:
  /api/v1/auth/sign-up:
    post:
      summary: User Sign-Up
      description: Creates a new user account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  minLength: 8
                  example: securepassword
              required:
                - email
                - password
      responses:
        "201":
          description: User created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User created successfully
        "400":
          description: Validation error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: string
        "500":
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error

  /api/v1/auth/sign-in:
    post:
      summary: User Sign-In
      description: Authenticates a user and returns a token in an HTTP-only cookie.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  minLength: 8
                  example: securepassword
              required:
                - email
                - password
      responses:
        "200":
          description: User authenticated successfully.
          headers:
            Set-Cookie:
              description: HTTP-only cookie containing the JWT token.
              schema:
                type: string
                example: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...; HttpOnly; Secure; SameSite=Strict; Max-Age=3600
        "400":
          description: Validation error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: string
        "401":
          description: Invalid credentials.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid credentials
        "500":
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error

  /api/v1/products:
    post:
      summary: Create a new product
      description: Creates a new product with the provided name and category ID.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the product
                categoryId:
                  type: string
                  description: UUID of the category
              required:
                - name
                - categoryId
      responses:
        "201":
          description: Product created successfully.
        "400":
          description: Validation error.
        "500":
          description: Internal server error.

  /api/v1/products/{id}:
    get:
      summary: Get product by ID
      description: Retrieves a product by its ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID of the product
      responses:
        "200":
          description: Product retrieved successfully.
        "404":
          description: Product not found.
        "500":
          description: Internal server error.

    put:
      summary: Update a product
      description: Updates a product's details by its ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID of the product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Updated name of the product
                categoryId:
                  type: string
                  description: Updated category ID of the product
      responses:
        "200":
          description: Product updated successfully.
        "400":
          description: Validation error.
        "500":
          description: Internal server error.

    delete:
      summary: Delete a product
      description: Deletes a product by its ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID of the product
      responses:
        "200":
          description: Product deleted successfully.
        "500":
          description: Internal server error.
